# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Auxiliar cpp function to obtain the probability for a vector x.
#' @param input numeric value with the information.
#' @export
#' @return returns the pmf for a vector.
aux_BP_Laksh <- function(input) {
    .Call('_MultivDists_aux_BP_Laksh', PACKAGE = 'MultivDists', input)
}

